### ISSUE TITLE
Classify the papers we've read.

### ISSUE THREAD

**Issue by BreezeShane** [neet-cv/ml.akasaki.space#150]
Hoping for the convenience to read the papers with stronger pertinence.....

**Comment by BreezeShane** [comment]
> > Hoping for the convenience to read the papers with stronger pertinence.....
> 
> Hold on. We're gonna use [Docusaurus 2](https://docusaurus.io/) which could be more convenient classifying posts instead of vuepress. After the replacement, we'll launch some kind of classification project. Hopefully you'd like to give a hand at that time.

My pleasure!

**Comment by visualDust** [comment]
solved #81 #77 and more. We've moved to docusaurus2. try it on.

**Comment by visualDust** [comment]
oops, forgot we'd continue on "Classify the papers we've read."

**Comment by visualDust** [comment]
@lideming any idea to make tags or classification availiable?

**Comment by visualDust** [comment]
#176 fixed. classified by tags
