### ISSUE TITLE
Research for Scene Graph Generation Model

### ISSUE THREAD

**Issue by PommesPeter** [neet-cv/ml.akasaki.space#187]
There are some related paper blow:

- [ ] Image Retrieval using Scene Graphs
- [ ] Scene Graph Generation by Iterative Message Passing
- [ ] Learning to Compose Dynamic Tree Structures for Visual Contexts
- [ ] Unbiased Scene Graph Generation from Biased Training
- [ ] Energy-Based Learning for Scene Graph Generation
- [ ] RU-Net: Regularized Unrolling Network for Scene Graph Generation
- [ ] Decomposed Prototype Learning for Few-Shot Scene Graph Generation (CVPR 2022)
- [ ] Devil's on the Edges: Selective Quad Attention for Scene Graph Generation (CVPR 2023)
- [ ] Panoptic Video Scene Graph Generation (CVPR 2023)
- [ ] Fast Contextual Scene Graph Generation with Unbiased Context Augmentation (CVPR 2023)
- [ ] Unbiased Scene Graph Generation in Videos (CVPR 2023)
- [ ] IS-GGT: Iterative Scene Graph Generation With Generative Transformers (CVPR 2023)

**Comment by lideming** [comment]
别卷了

**Comment by visualDust** [comment]
> 别卷了

快帮我想 [这个](https://github.com/visualDust/neetbox/issues/20)

**Comment by PommesPeter** [comment]
> > 别卷了
> 
> 快帮我想 [这个](https://github.com/visualDust/neetbox/issues/20)

呜呜呜

**Comment by PommesPeter** [comment]
i am not research for this topic, close
