### ISSUE TITLE
添加自动排号功能

### ISSUE THREAD

**Issue by PommesPeter** [neet-cv/ml.akasaki.space#37]
无论谁上传一篇都能够自动编号，不用再看目前排到几号——针对论文日志

初步想法使用github action来做

**Comment by lideming** [comment]
之前编号是为了指定顺序，如果不用编号，可以按日期排序（要在 md 里写日期），也可以按名称排序

**Comment by lideming** [comment]
> 那要不就时间排序？

可以

**Comment by PommesPeter** [comment]
好！

**Comment by visualDust** [comment]
#43 之后应该会处理自动标号的问题（

**Comment by visualDust** [comment]
#176 fucked this up. we do not need to number the file anymore
