### ISSUE TITLE
Use tabs to split TensorFlow and PyTorch code

### ISSUE THREAD

**Issue by lideming** [neet-cv/ml.akasaki.space#77]
Consider using this VuePress plugin: https://github.com/pskordilakis/vuepress-plugin-tabs

**Comment by visualDust** [comment]
how

**Comment by lideming** [comment]
I think that plugin is dead, use this one instead: https://github.com/superbiger/vuepress-plugin-tabs

## Usage
`````
:::: tabs

::: tab TensorFlow
```py
# TensorFlow code
# TensorFlow code
# TensorFlow code
```
:::

::: tab PyTorch
```py
# PyTorch code
# PyTorch code
# PyTorch code
```
:::

::::
`````

**Comment by coronaPolvo** [comment]
Some articles differ not only in the codes but also in the text description. @lideming

**Comment by visualDust** [comment]
话说你在校基地吗，我去摸会鱼 @lideming

**Comment by visualDust** [comment]
看来不在 ![image](https://user-images.githubusercontent.com/33346934/119596035-14588880-be11-11eb-8e56-984f4291373e.png)

**Comment by lideming** [comment]
@coronaPolvo 文本等内容也可以放在 tab 里。然后如果有个全局的默认语言切换开关就好了（

**Comment by visualDust** [comment]
I've tried in the tftorchcombinetest branch.
It's not working as I think.

**Comment by visualDust** [comment]
Is there any progress on this issue now?

**Comment by visualDust** [comment]
Is there any progress on this issue now?  @lideming

**Comment by lideming** [comment]
gugugu

**Comment by visualDust** [comment]
#150 continue in another issue
